In [1]:
import numpy

In [2]:
import numpy as np

In [3]:
x=np.array([1,2,3,4,5,6])
print(x)

[1 2 3 4 5 6]


In [4]:
print(type(x))

<class 'numpy.ndarray'>


In [5]:
l=[1,2,3,4,5,6]
print(l)
print(type(l))

[1, 2, 3, 4, 5, 6]
<class 'list'>


# array is faster than list

In [6]:
%timeit [i**5 for i in range(1,10)]

2.3 µs ± 31.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [7]:
import numpy as np

In [9]:
%timeit np.arange(1,10)**5

4.78 µs ± 41.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [10]:
%timeit np.arange(1,10)**5

4.87 µs ± 39.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# creating NUMPY array

In [11]:
import numpy as rishi
x=rishi.array([1,2,3])
print(x)

[1 2 3]


In [12]:
import numpy as rishi
x=np.array([1,2,3])
print(x)

[1 2 3]


In [13]:
import numpy as ola
x=np.array([1,2,3])
print(x)

[1 2 3]


In [18]:
import numpy as np
x=np.array([11,22,33])
print(x)
print(type(x))
print(x.ndim)

[11 22 33]
<class 'numpy.ndarray'>
1


In [16]:
import numpy as np
x=np.array([[11,22,33]])
print(x)
print(type(x))
print(x.ndim)

[[11 22 33]]
<class 'numpy.ndarray'>
2


In [17]:
import numpy as np
x=np.array([[[11,22,33]]])
print(x)
print(type(x))
print(x.ndim)

[[[11 22 33]]]
<class 'numpy.ndarray'>
3


In [21]:
import numpy as np
m=[]
for i in range(5):
    num=input('Enter number')
    m.append(num)

y=np.array(m)
print(y)
print(type(y))

Enter number 1
Enter number 2
Enter number 3
Enter number 4
Enter number 5


['1' '2' '3' '4' '5']
<class 'numpy.ndarray'>


# creating 2D array

In [22]:
ar2=np.array([[1,2,3,4],[5,6,7,8],[11,22,33,44]])
print(ar2)
print(ar2.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [11 22 33 44]]
2


In [24]:
ar2=np.array([[1,2,3,4],[5,6,7,8],[11,22,33,55]])
print(ar2)
print(ar2.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [11 22 33 55]]
2


In [25]:
ar2=np.array([[1,2,3,4,5,6,7],[5,6,7,8,9,10,21],[11,22,33,55,66,77,88]])
print(ar2)
print(ar2.ndim)

[[ 1  2  3  4  5  6  7]
 [ 5  6  7  8  9 10 21]
 [11 22 33 55 66 77 88]]
2


# creating a 3D array

In [26]:
ar3=np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,10]]])
print(ar3)
print(ar3.ndim)

[[[ 1  2  3  4]
  [ 4  5  6  7]
  [ 7  8  9 10]]]
3


# creating a multidimensional array

In [28]:
arn=np.array([1,2,3,4],ndmin=15)
print(arn)
print(arn.ndim)

[[[[[[[[[[[[[[[1 2 3 4]]]]]]]]]]]]]]]
15


In [30]:
arn=np.array(([1,2,3,4],[5,6,7,8]),ndmin=25)
print(arn)
print(arn.ndim)

[[[[[[[[[[[[[[[[[[[[[[[[[1 2 3 4]
                        [5 6 7 8]]]]]]]]]]]]]]]]]]]]]]]]]
25
