# DATA Types in NUMPY

In [1]:
import numpy as np
x=np.array([1,2,3,4])
print('The datat type is:',x.dtype)

The datat type is: int32


In [2]:
x1=np.array([1.2,2.3,4.5,3.8,5.5])
print('The data type is:',x1.dtype)

The data type is: float64


In [3]:
x2=np.array(['apple','chiku','orange','papaya'])
print('The data type is:',x2.dtype)

The data type is: <U6


In [4]:
x3=np.array(['apple','chiku','orange','papaya',1,2,3,3,3.5,5.5])
print('The data type is:',x3.dtype)

The data type is: <U32


# converting one data type into another data type

In [6]:
x=np.array([1,2,3,4,5])
print(x)
print(x.dtype)

x1=np.array([1,2,3,4,5],dtype=np.int16)
print(x1)
print(x1.dtype)

[1 2 3 4 5]
int32
[1 2 3 4 5]
int16


In [7]:
x=np.array([1,2,3,4,5])
print(x)
print(x.dtype)

x1=np.array([1,2,3,4,5],dtype='f')
print(x1)
print(x1.dtype)

[1 2 3 4 5]
int32
[1. 2. 3. 4. 5.]
float32


In [9]:
m=np.array([1,2,3,4])
print(m)
print(m.dtype)

m1=np.float64(m)
print(m1)
print(m1.dtype)

[1 2 3 4]
int32
[1. 2. 3. 4.]
float64


In [10]:
m=np.array([1,2,3,4])
print(m)
print(m.dtype)

m1=np.float64(m)
print(m1)
print(m1.dtype)

m2=np.int64(m1)
print(m2)
print(m2.dtype)

[1 2 3 4]
int32
[1. 2. 3. 4.]
float64
[1 2 3 4]
int64


In [11]:
x=np.array([1,2,3,4])
y=x.astype(complex)
print(x)
print(x.dtype)
print(y)
print(y.dtype)

[1 2 3 4]
int32
[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
complex128


# arithmatic operations in munpy array

"""addition"""

In [13]:
x=np.array([1,2,3,4])
y=x+3
print(y)

[4 5 6 7]


In [14]:
x=np.array([1,2,3,4,5])
m=np.array([5,6,7,8,9])
y=x+m
print(y)

[ 6  8 10 12 14]


In [15]:
x=np.array([1,2,3,4,5])
m=np.array([5,6,7,8,9])
y=np.add(x,m)
print(y)

[ 6  8 10 12 14]


# Subtraction

In [16]:
x=np.array([1,2,3,4,5])
y=x-3
print(y)

[-2 -1  0  1  2]


In [17]:
x=np.array([1,2,3,4,5])
m=np.array([5,6,7,8,9])
y=x-m
print(y)

[-4 -4 -4 -4 -4]


In [18]:
x=np.array([1,2,3,4,5])
m=np.array([5,6,7,8,9])
y=np.subtract(x,m)
print(y)

[-4 -4 -4 -4 -4]


# Multiplication

In [19]:
x=np.array([1,2,3,4])
y=x*3
print(y)

[ 3  6  9 12]


In [20]:
x=np.array([1,2,3,4,5])
m=np.array([5,6,7,8,9])
y=np.multiply(x,m)
print(y)

[ 5 12 21 32 45]


In [21]:
x=np.array([1,2,3,4,5])
m=np.array([5,6,7,8,9])
y=x*m
print(y)

[ 5 12 21 32 45]


# division

In [22]:
x=np.array([1,2,3,4])
y=x/3
print(y)

[0.33333333 0.66666667 1.         1.33333333]


In [23]:
x=np.array([1,2,3,4,5])
m=np.array([5,6,7,8,9])
y=np.divide(x,m)
print(y)

[0.2        0.33333333 0.42857143 0.5        0.55555556]


# modulous

In [24]:
x=np.array([11,22,33,44])
y=x%3
print(y)

[2 1 0 2]


In [25]:
x=np.array([1,2,3,4,5])
m=np.array([5,6,7,8,9])
y=x%m
print(y)

[1 2 3 4 5]


In [27]:
x=np.array([1,2,3,4,5])
m=np.array([5,6,7,8,9])
y=np.mod(x,m)
print(y)

[1 2 3 4 5]


# reciprocal

In [28]:
a=np.array([21,22,23,24])
b=np.reciprocal(a)
print(b)

[0 0 0 0]


# arithematic operations in 2D array

In [31]:
n1=np.array([[1,2,3,4],[5,6,7,8]])
n2=np.array([[1,2,3,4],[5,6,7,8]])
x=n1+n2
print(x)

[[ 2  4  6  8]
 [10 12 14 16]]


In [32]:
n1=np.array([[1,2,3,4],[5,6,7,8]])
n2=np.array([[1,2,3,4],[5,6,7,8]])
x=n1-n2
print(x)

[[0 0 0 0]
 [0 0 0 0]]


In [33]:
n1=np.array([[1,2,3,4],[5,6,7,8]])
n2=np.array([[1,2,3,4],[5,6,7,8]])
x=n1*n2
print(x)

[[ 1  4  9 16]
 [25 36 49 64]]


In [34]:
n1=np.array([[1,2,3,4],[5,6,7,8]])
n2=np.array([[1,2,3,4],[5,6,7,8]])
x=n1/n2
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [35]:
n1=np.array([[1,2,3,4],[5,6,7,8]])
n2=np.array([[1,2,3,4],[5,6,7,8]])
x=n1%n2
print(x)

[[0 0 0 0]
 [0 0 0 0]]


# arithematic operations in 3D array

In [39]:
n1=np.array([[[1,2,3,4],[5,6,7,8]]])
n2=np.array([[[1,2,3,4],[5,6,7,8]]])
x=n1+n2
print(x)
print(x.ndim)

[[[ 2  4  6  8]
  [10 12 14 16]]]
3


In [40]:
n1=np.array([[[1,2,3,4],[5,6,7,8]]])
n2=np.array([[[1,2,3,4],[5,6,7,8]]])
x=n1-n2
print(x)
print(x.ndim)

[[[0 0 0 0]
  [0 0 0 0]]]
3


In [41]:
n1=np.array([[[1,2,3,4],[5,6,7,8]]])
n2=np.array([[[1,2,3,4],[5,6,7,8]]])
x=n1*n2
print(x)
print(x.ndim)

[[[ 1  4  9 16]
  [25 36 49 64]]]
3


In [42]:
n1=np.array([[[1,2,3,4],[5,6,7,8]]])
n2=np.array([[[1,2,3,4],[5,6,7,8]]])
x=n1/n2
print(x)
print(x.ndim)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
3


# arithematic functions

# max and min alongwith index number

In [43]:
import numpy as np
a=np.array([1,3,2,56,34,67,22,33,44,66])
print(np.max(a))
print(np.min(a))

67
1


In [45]:
import numpy as np
a=np.array([1,3,2,56,34,67,22,33,44,66])
print(np.max(a),np.argmax(a))
print(np.min(a),np.argmin(b))

67 5
1 0


In [47]:
m=np.array([[11,23,45,99,66],[57,100,150,89,33]])
print(m)
print(m.ndim)
n=np.min(m,axis=0)
print(n)

[[ 11  23  45  99  66]
 [ 57 100 150  89  33]]
2
[11 23 45 89 33]


In [48]:
m=np.array([[11,23,45,99,66],[57,100,150,89,33]])
print(m)
print(m.ndim)
n=np.min(m,axis=1)
print(n)

[[ 11  23  45  99  66]
 [ 57 100 150  89  33]]
2
[11 33]


In [49]:
m=np.array([[11,23,45,99,66],[57,100,150,89,33]])
print(m)
print(m.ndim)
n=np.max(m,axis=0)
print(n)

[[ 11  23  45  99  66]
 [ 57 100 150  89  33]]
2
[ 57 100 150  99  66]


In [50]:
m=np.array([[11,23,45,99,66],[57,100,150,89,33]])
print(m)
print(m.ndim)
n=np.max(m,axis=1)
print(n)

[[ 11  23  45  99  66]
 [ 57 100 150  89  33]]
2
[ 99 150]


# square root

In [51]:
a=np.array([2,4,5,7,1])
print(np.sqrt(a))

[1.41421356 2.         2.23606798 2.64575131 1.        ]


In [52]:
a=np.array([4,9,16,25,36])
print(np.sqrt(a))

[2. 3. 4. 5. 6.]


In [54]:
a=np.array([[2,4,5,7,1],[11,22,33,44,55]])
print(np.sqrt(a))

[[1.41421356 2.         2.23606798 2.64575131 1.        ]
 [3.31662479 4.69041576 5.74456265 6.63324958 7.41619849]]


# Sin value and Cos value

In [55]:
a=np.array([1,2,3])
print(np.sin(a))

[0.84147098 0.90929743 0.14112001]


In [57]:
a=np.array([[1,2,3],[4,5,6]])
print(np.sin(a))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


In [56]:
a=np.array([1,2,3])
print(np.cos(a))

[ 0.54030231 -0.41614684 -0.9899925 ]


In [58]:
a=np.array([[1,2,3],[4,5,6]])
print(np.cos(a))

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]


# cumsum

In [59]:
a=np.array([1,2,3,4])
print(np.cumsum(a))

[ 1  3  6 10]


In [61]:
a=np.array([[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]])
print(np.cumsum(a))

[  1   3   6  10  15  21  28  36  45  55  56  58  61  65  70  76  83  91
 100 110]


# broadcasting Numpy array

In [67]:
n1=np.array([1,2,3,4])
n2=np.array([2,3,4,])
print(n1.shape)
print(n2.shape)
x=n1+n2
print(x)

(4,)
(3,)


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [70]:
n1=np.array([1,2,3,4])
print(n1.shape)
print(n1)
print()

n2=np.array([[1],[2],[3],[4]])
print(n2)
print(n2.shape)
print()
print(n1+n2)

(4,)
[1 2 3 4]

[[1]
 [2]
 [3]
 [4]]
(4, 1)

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


In [76]:
x=np.array([[4],[3]])
print(x.shape)
print(x)
print()
y=np.array([[6,7,3],[1,3,2]])
print(y.shape)
print(y)
print()

print(x+y)
print()
print(x-y)
print()
print(x*y)
print()
print(x/y)

(2, 1)
[[4]
 [3]]

(2, 3)
[[6 7 3]
 [1 3 2]]

[[10 11  7]
 [ 4  6  5]]

[[-2 -3  1]
 [ 2  0  1]]

[[24 28 12]
 [ 3  9  6]]

[[0.66666667 0.57142857 1.33333333]
 [3.         1.         1.5       ]]


In [82]:
x=np.array([[4,8],[3,7],[5,9]])
print(x.shape)
print(x)
print()
y=np.array([[6,7,2],[1,3,4],[1,2,3]])
print(y.shape)
print(y)
print()

print(x+y)

(3, 2)
[[4 8]
 [3 7]
 [5 9]]

(3, 3)
[[6 7 2]
 [1 3 4]
 [1 2 3]]



ValueError: operands could not be broadcast together with shapes (3,2) (3,3) 

In [83]:
x=np.array([[4],[3],[5]])
print(x.shape)
print(x)
print()
y=np.array([[6,7,2],[1,3,4],[1,2,3]])
print(y.shape)
print(y)
print()

print(x+y)

(3, 1)
[[4]
 [3]
 [5]]

(3, 3)
[[6 7 2]
 [1 3 4]
 [1 2 3]]

[[10 11  6]
 [ 4  6  7]
 [ 6  7  8]]


In [84]:
x=np.array([[4,3,1],[3,5,8],[5,4,3]])
print(x.shape)
print(x)
print()
y=np.array([[6,7,2],[1,3,4],[1,2,3]])
print(y.shape)
print(y)
print()

print(x+y)

(3, 3)
[[4 3 1]
 [3 5 8]
 [5 4 3]]

(3, 3)
[[6 7 2]
 [1 3 4]
 [1 2 3]]

[[10 10  3]
 [ 4  8 12]
 [ 6  6  6]]
