# Split array

In [4]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
print(a)
print()
v=np.array_split(a,3)
print(v)
print(type(v))
print(v[0])

[1 2 3 4 5 6 7 8 9]

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
<class 'list'>
[1 2 3]


In [6]:
a=np.array([[1,2,],[4,5],[6,7],[8,9]])
print(a)
print()
v=np.array_split(a,4,axis=1)
print(v)

[[1 2]
 [4 5]
 [6 7]
 [8 9]]

[array([[1],
       [4],
       [6],
       [8]]), array([[2],
       [5],
       [7],
       [9]]), array([], shape=(4, 0), dtype=int32), array([], shape=(4, 0), dtype=int32)]


In [7]:
a=np.array([[1,2,],[4,5],[6,7],[8,9]])
print(a)
print()
v=np.array_split(a,4,axis=0)
print(v)

[[1 2]
 [4 5]
 [6 7]
 [8 9]]

[array([[1, 2]]), array([[4, 5]]), array([[6, 7]]), array([[8, 9]])]


In [8]:
a=np.array([[1,2,],[4,5],[6,7],[8,9]])
print(a)
print()
v=np.array_split(a,2,axis=0)
print(v)

[[1 2]
 [4 5]
 [6 7]
 [8 9]]

[array([[1, 2],
       [4, 5]]), array([[6, 7],
       [8, 9]])]


# Search array

In [9]:
import numpy as np
a=np.array([1,2,3,4,5,4,2,6,1,8])
x=np.where(a==3)
print(x)

(array([2], dtype=int64),)


In [10]:
import numpy as np
a=np.array([1,2,3,4,5,4,2,6,1,8])
x=np.where(a%2==0)
print(x)

(array([1, 3, 5, 6, 7, 9], dtype=int64),)


# Search sorted array

In [11]:
z=np.array([11,12,13,14,18,19])
x=np.searchsorted(z,15)
print(x)

4


In [13]:
z=np.array([11,12,13,14,18,19,22,23])
x=np.searchsorted(z,20,side='right')
print(x)

6


In [14]:
z=np.array([11,12,13,14,18,19,22,23])
x=np.searchsorted(z,20,side='left')
print(x)

6


In [15]:
p=np.array([21,22,23,31,32,33])
n=np.searchsorted(p,[25,28,30])
print(n)

[3 3 3]


# sort array

In [16]:
a=np.array([12,78,87,43,65,90,17,80,-32])
print(np.sort(a))

[-32  12  17  43  65  78  80  87  90]


In [18]:
b=np.array(['o','w','k','z','a','n','b','q','t','y'])
print(np.sort(b))

['a' 'b' 'k' 'n' 'o' 'q' 't' 'w' 'y' 'z']


In [20]:
a=np.array([[48,65,22,],[11,22,33],[-23,87,55]])
print(a)
print(a.ndim)
print()
print(np.sort(a))

[[ 48  65  22]
 [ 11  22  33]
 [-23  87  55]]
2

[[ 22  48  65]
 [ 11  22  33]
 [-23  55  87]]


In [22]:
x=np.array([[[14,18,-9],[11,22,33],[12,89,-100]]])
print(x)
print(x.ndim)
print()
print(np.sort(x))

[[[  14   18   -9]
  [  11   22   33]
  [  12   89 -100]]]
3

[[[  -9   14   18]
  [  11   22   33]
  [-100   12   89]]]


# Filter array

In [24]:
a=np.array([1,2,3,22,45,68,99])
f=[True,False,True,False,True,False,True]
b=a[f]
print(b)

[ 1  3 45 99]


# Shuffle function

In [30]:
import numpy as np
k=np.array([11,44,777,88,33,101,200,35,78])
print('The array is:',k)
np.random.shuffle(k)
print('Now the array is:',k)

The array is: [ 11  44 777  88  33 101 200  35  78]
Now the array is: [ 44  35  33 777  11 200 101  88  78]


# Unique function

In [32]:
k=np.array([12,14,11,99,87,45,33,88,33,11,12,99,33,45,14,12])
print(k)
x=np.unique(k)
print(x)

[12 14 11 99 87 45 33 88 33 11 12 99 33 45 14 12]
[11 12 14 33 45 87 88 99]


In [33]:
k=np.array([12,14,11,99,87,45,33,88,33,11,12,99,33,45,14,12])
print(k)
x=np.unique(k,return_index=True)
print(x)

[12 14 11 99 87 45 33 88 33 11 12 99 33 45 14 12]
(array([11, 12, 14, 33, 45, 87, 88, 99]), array([2, 0, 1, 6, 5, 4, 7, 3], dtype=int64))


In [35]:
k=np.array([12,14,11,99,87,45,33,88,33,11,12,99,33,45,14,12])
print(k)
print()
x=np.unique(k,return_index=True,return_counts=True)
print(x)

[12 14 11 99 87 45 33 88 33 11 12 99 33 45 14 12]

(array([11, 12, 14, 33, 45, 87, 88, 99]), array([2, 0, 1, 6, 5, 4, 7, 3], dtype=int64), array([2, 3, 2, 3, 2, 1, 1, 2], dtype=int64))


# Resize function

In [39]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
print(a)
print(a.ndim)
print(a.shape)
b=np.resize(a,(3,2))
print('Now the size is:')
print(b)
print('the dimension is',b.ndim)
print('the shape is',b.shape)

[1 2 3 4 5 6 7 8 9]
1
(9,)
Now the size is:
[[1 2]
 [3 4]
 [5 6]]
the dimension is 2
the shape is (3, 2)


# Insert function

In [41]:
n=np.array([1,2,3,4,5,6,7,8,9])
print(n)
v=np.insert(n,3,200)
print(v)

[1 2 3 4 5 6 7 8 9]
[  1   2   3 200   4   5   6   7   8   9]


In [42]:
n=np.array([1,2,3,4,5,6,7,8,9])
print(n)
v=np.insert(n,(3,5),(20,40))
print(v)

[1 2 3 4 5 6 7 8 9]
[ 1  2  3 20  4  5 40  6  7  8  9]


# Insert function-- 2D array

In [45]:
x=np.array([[2,7,5,3,8],[1,4,2,6,9]])
print(x)
print()
x1=np.insert(x,2,24,axis=1)
print(x1)

[[2 7 5 3 8]
 [1 4 2 6 9]]

[[ 2  7 24  5  3  8]
 [ 1  4 24  2  6  9]]


In [46]:
x=np.array([[2,7,5,3,8],[1,4,2,6,9]])
print(x)
print()
x1=np.insert(x,2,24,axis=0)
print(x1)

[[2 7 5 3 8]
 [1 4 2 6 9]]

[[ 2  7  5  3  8]
 [ 1  4  2  6  9]
 [24 24 24 24 24]]


In [47]:
x=np.array([[2,7,5,3,8],[1,4,2,6,9]])
print(x)
print()
x1=np.insert(x,2,[25,26,27,28,29],axis=0)
print(x1)

[[2 7 5 3 8]
 [1 4 2 6 9]]

[[ 2  7  5  3  8]
 [ 1  4  2  6  9]
 [25 26 27 28 29]]


# append

In [48]:
import numpy as np
a=np.array([12,13,14])
x=np.append(a,3.5)
print(x)

[12.  13.  14.   3.5]


In [50]:
x=np.array([[2,7,9,6,8],[4,5,7,1,3]])
m=np.append(x,[[-4,-5,-6,-7,-8]],axis=0)
print(x)
print()
print(m)

[[2 7 9 6 8]
 [4 5 7 1 3]]

[[ 2  7  9  6  8]
 [ 4  5  7  1  3]
 [-4 -5 -6 -7 -8]]


# Delete function

In [51]:
a=np.array([12,13,14,15])
print(a)
print()
d=np.delete(a,[1])
print(d)

[12 13 14 15]

[12 14 15]


In [53]:
x=np.array([[2,5,4,8,9],[5,11,3,7,9],[22,44,88,65,99]])
print(x)
print()
m=np.delete(x,0,axis=0)
print(m)

[[ 2  5  4  8  9]
 [ 5 11  3  7  9]
 [22 44 88 65 99]]

[[ 5 11  3  7  9]
 [22 44 88 65 99]]
