# Numpy array with all its element values as zero

In [1]:
import numpy as np
ar=np.zeros(5)
print(ar)
print(ar.ndim)

[0. 0. 0. 0. 0.]
1


In [2]:
ar1=np.zeros((4,3))
print(ar1)
print(ar1.ndim)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2


In [4]:
ar2=np.zeros(((1,3,4)))
print(ar2)
print(ar2.ndim)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
3


In [5]:
ar2=np.zeros(((2,3,4)))
print(ar2)
print(ar2.ndim)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
3


In [6]:
ar2=np.zeros(((4,3,4)))
print(ar2)
print(ar2.ndim)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
3


# Numpy array with all its element values as one

In [7]:
arr=np.ones(6)
print(arr)
print(arr.ndim)

[1. 1. 1. 1. 1. 1.]
1


In [8]:
arr1=np.ones((4,5))
print(arr1)
print(arr1.ndim)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
2


In [14]:
arr2=np.ones((1,3,3))
print(arr2)
print('dimension is:',arr2.ndim)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
dimension is: 3


In [13]:
arr2=np.ones((3,3,3))
print(arr2)
print('dimension is:',arr2.ndim)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
dimension is: 3


In [15]:
arr2=np.ones((3,3,3),dtype='bool')
print(arr2)
print('dimension is:',arr2.ndim)

[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]]
dimension is: 3


# creating an empty array

In [16]:
k=np.empty(3)
print(k)
print(k.ndim)

[0. 0. 0.]
1


In [17]:
l=np.empty((3,3))
print(l)
print(l.ndim)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
2


In [18]:
l=np.empty((4,3))
print(l)
print(l.ndim)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2


# creating an array with range

In [19]:
b=np.arange(1,21)
print(b)
print(b.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1


In [20]:
b=np.arange(3,101)
print(b)
print(b.ndim)

[  3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20
  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38
  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56
  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74
  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92
  93  94  95  96  97  98  99 100]
1


In [21]:
b=np.arange(3,101,3)
print(b)
print(b.ndim)

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]
1


In [22]:
b=np.arange(5,1001,5)
print(b)
print(b.ndim)

[   5   10   15   20   25   30   35   40   45   50   55   60   65   70
   75   80   85   90   95  100  105  110  115  120  125  130  135  140
  145  150  155  160  165  170  175  180  185  190  195  200  205  210
  215  220  225  230  235  240  245  250  255  260  265  270  275  280
  285  290  295  300  305  310  315  320  325  330  335  340  345  350
  355  360  365  370  375  380  385  390  395  400  405  410  415  420
  425  430  435  440  445  450  455  460  465  470  475  480  485  490
  495  500  505  510  515  520  525  530  535  540  545  550  555  560
  565  570  575  580  585  590  595  600  605  610  615  620  625  630
  635  640  645  650  655  660  665  670  675  680  685  690  695  700
  705  710  715  720  725  730  735  740  745  750  755  760  765  770
  775  780  785  790  795  800  805  810  815  820  825  830  835  840
  845  850  855  860  865  870  875  880  885  890  895  900  905  910
  915  920  925  930  935  940  945  950  955  960  965  970  975  980
  985 

# linspace

In [23]:
a=np.linspace(1,10,5)
print(a)
print(a.ndim)

[ 1.    3.25  5.5   7.75 10.  ]
1


In [24]:
a=np.linspace(1,30,8)
print(a)
print(a.ndim)

[ 1.          5.14285714  9.28571429 13.42857143 17.57142857 21.71428571
 25.85714286 30.        ]
1


In [25]:
a=np.linspace(5,20,6)
print(a)
print(a.ndim)

[ 5.  8. 11. 14. 17. 20.]
1


# shape function

In [27]:
ar=np.array([[1,2,3],[11,22,33]])
print(ar)
print(ar.ndim)
print(ar.shape)

[[ 1  2  3]
 [11 22 33]]
2
(2, 3)


In [28]:
ar=np.array([[1,2,3],[11,22,33],[13,15,16]])
print(ar)
print(ar.ndim)
print(ar.shape)

[[ 1  2  3]
 [11 22 33]
 [13 15 16]]
2
(3, 3)


In [29]:
ar=np.array([[[1,2,3],[5,6,7],[7,8,9],[11,22,33]]])
print(ar)
print(ar.ndim)
print(ar.shape)

[[[ 1  2  3]
  [ 5  6  7]
  [ 7  8  9]
  [11 22 33]]]
3
(1, 4, 3)


# reshape function

In [32]:
m=np.array([1,2,3,4,5,6,7,8,9,10])
n=m.reshape(2,5)
print(n)
print(n.ndim)
print()
print(m)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2

[ 1  2  3  4  5  6  7  8  9 10]


In [34]:
m=np.array([1,2,3,4,5,6,7,8,9])
n=m.reshape(3,3)
print(n)
print(n.ndim)
print()
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2

[1 2 3 4 5 6 7 8 9]


In [35]:
m=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
n=m.reshape(3,2,3)
print(n)
print(n.ndim)
print()
print(m)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [37]:
m=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
n=m.reshape(3,2,3)
print(n)
print(n.ndim)
print()
print(m)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [40]:
x=np.array([[1,2,3,4],[4,5,6,7],[6,7,8,9]])
print(x.ndim)
print(x)
print()
y=x.reshape(2,1,2,3)
print()
print(y)
print()
print(y.ndim)

2
[[1 2 3 4]
 [4 5 6 7]
 [6 7 8 9]]


[[[[1 2 3]
   [4 4 5]]]


 [[[6 7 6]
   [7 8 9]]]]

4


# ravel & flatten -- converts multidimensional array into 1D array

In [43]:
m=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print('Dimension is:',m.ndim)
print()
n=m.ravel()
print(n)
print('now the new dimension is',n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Dimension is: 3

[1 2 3 4 5 6 7 8 9]
now the new dimension is 1


In [44]:
m=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print('Dimension is:',m.ndim)
print()
n=m.flatten()
print(n)
print('now the new dimension is',n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
Dimension is: 3

[1 2 3 4 5 6 7 8 9]
now the new dimension is 1


In [49]:
c=np.array([[[[1,2,3],[4,5,6],[11,22,33],[55,66,77]]]])
print(c)
print(c.ndim)
print()
d=c.flatten()
print(d)
print('Now dimension is :',d.ndim)

[[[[ 1  2  3]
   [ 4  5  6]
   [11 22 33]
   [55 66 77]]]]
4

[ 1  2  3  4  5  6 11 22 33 55 66 77]
Now dimension is : 1


In [50]:
c=np.array([[[[1,2,3],[4,5,6],[11,22,33],[55,66,77]]]])
print(c)
print(c.ndim)
print()
d=c.ravel()
print(d)
print('Now dimension is :',d.ndim)

[[[[ 1  2  3]
   [ 4  5  6]
   [11 22 33]
   [55 66 77]]]]
4

[ 1  2  3  4  5  6 11 22 33 55 66 77]
Now dimension is : 1


# Create an array with diagnol elements filled  with 1- identity matrix

In [51]:
arr=np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [52]:
ar1=np.eye(3,6)
print(ar1)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [53]:
ar1=np.eye(5,8)
print(ar1)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]


# rand function -- create numpy array with random numbers

# rand()-- random module's rand() method returns a random float between 0 and 1 

In [56]:
var=np.random.rand(5)
print(var)

[0.99346915 0.35368709 0.59877716 0.93192332 0.9127547 ]


In [ ]:
[0.27464945 0.82398566 0.02690527 0.27637313 0.2857531 ]

In [ ]:
[0.72750777 0.84422993 0.86652419 0.08057546 0.07264946]

In [58]:
var=np.random.rand(3,4)
print(var)

[[0.10097855 0.46844681 0.47757511 0.26877576]
 [0.35658693 0.50853635 0.6401446  0.43994135]
 [0.64901784 0.43799045 0.10545477 0.26064289]]


In [60]:
var=np.random.rand(2,3,4)
print(var)

[[[0.24968567 0.30032548 0.78027779 0.40753625]
  [0.51615794 0.13361161 0.40666389 0.22745444]
  [0.12735989 0.51562916 0.7525443  0.40189072]]

 [[0.40376532 0.12721904 0.74589212 0.53103906]
  [0.38628315 0.2570879  0.63807986 0.79598742]
  [0.03805211 0.77142286 0.07922626 0.78424678]]]


# randn()- The function is used to generate a value close to zero and this may return positive as well as negative

In [62]:
n=np.random.randn(5)
print(n)
print('the dimension is:',n.ndim)

[-1.16863175 -0.31448187 -0.31714863 -0.635963    0.44536864]
the dimension is: 1


In [63]:
n=np.random.randn(2,5)
print(n)
print(n.ndim)
print(n.shape)

[[-0.30893307 -0.91125405 -0.17316345 -0.21675361  1.24982008]
 [ 0.71894308 -0.51071828 -0.98824823  0.23885687  0.35041212]]
2
(2, 5)


In [64]:
n=np.random.randn(1,2,5)
print(n)
print(n.ndim)
print(n.shape)

[[[ 1.05677193  1.05572589 -1.18797758  1.94193302  0.35524293]
  [ 1.35294521 -0.23814099  1.48961397 -0.10638331  0.96553574]]]
3
(1, 2, 5)


# randint

In [65]:
a=np.random.randint(4,20,5)
print(a)
print(a.ndim)

[17 16  9 12 11]
1


In [66]:
a=np.random.randint(4,100,8)
print(a)
print(a.ndim)

[68 79  8 98 52  9 23 49]
1


# ranf -- use for doing random sampling in numpy. It returns an array of specified shape and fills it with random floats in the half open interval between 0 and 1

In [68]:
x=np.random.ranf(4)
print(x)

[0.23778038 0.34819672 0.22868464 0.06635919]


In [70]:
x=np.random.ranf((2,4))
print(x)
print(x.ndim)

[[0.00448473 0.4954856  0.22054341 0.13741375]
 [0.03491298 0.69454881 0.1822704  0.76214061]]
2
