# Matrix

In [3]:
import numpy as np
a=np.matrix([[1,2,3],[1,2,3]])
print(a)
print(type(a))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>


In [4]:
b=np.array([[1,2,3],[1,2,3]])
print(b)
print(type(b))

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


# arethematic operations in matrix

In [7]:
print('we are talking about matrix')
a=np.matrix([[1,2,3],[1,2,3]])
c=np.matrix([[4,5,6],[4,5,6]])
print(a)
print()
print(c)
print()
print(a+c)
print()
print('We are talking about array')
n=np.array([[1,2,3],[1,2,3]])
m=np.array([[4,5,6],[4,5,6]])
print(n)
print()
print(m)
print()
print(n+m)

we are talking about matrix
[[1 2 3]
 [1 2 3]]

[[4 5 6]
 [4 5 6]]

[[5 7 9]
 [5 7 9]]

We are talking about array
[[1 2 3]
 [1 2 3]]

[[4 5 6]
 [4 5 6]]

[[5 7 9]
 [5 7 9]]


In [8]:
print('we are talking about matrix')
a=np.matrix([[1,2,3],[1,2,3]])
c=np.matrix([[4,5,6],[4,5,6]])
print(a)
print()
print(c)
print()
print(a-c)
print()
print('We are talking about array')
n=np.array([[1,2,3],[1,2,3]])
m=np.array([[4,5,6],[4,5,6]])
print(n)
print()
print(m)
print()
print(n-m)

we are talking about matrix
[[1 2 3]
 [1 2 3]]

[[4 5 6]
 [4 5 6]]

[[-3 -3 -3]
 [-3 -3 -3]]

We are talking about array
[[1 2 3]
 [1 2 3]]

[[4 5 6]
 [4 5 6]]

[[-3 -3 -3]
 [-3 -3 -3]]


In [13]:
print('we are talking about matrix')
a=np.matrix([[1,2],[3,4]])
b=np.matrix([[5,6],[7,8]])
print(a)
print()
print(b)
print()
l=a.dot(b)
print(l)
print(a*b)
print('we are talking about array')
m=np.array([[1,2],[3,4]])
n=np.array([[5,6],[7,8]])
print(m)
print()
print(n)
print()
print(m*n)

we are talking about matrix
[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
we are talking about array
[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[ 5 12]
 [21 32]]


In [16]:
print('we are talking about matrix')
a=np.matrix([[1,2],[3,4]])
b=np.matrix([[5,6],[7,8]])
print(a)
print()
print(b)
print()
print(b/a)
print('we are talking about array')
m=np.array([[1,2],[3,4]])
n=np.array([[5,6],[7,8]])
print(m)
print()
print(n)
print()
print(n/m)

we are talking about matrix
[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[5.         3.        ]
 [2.33333333 2.        ]]
we are talking about array
[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[5.         3.        ]
 [2.33333333 2.        ]]


# matrix functions

# transpose function --- interchage rows into column and column into rows and vice versa

In [18]:
a=np.matrix([[4,5,6],[14,16,18],[9,17,43]])
print(a)
print()
print(np.transpose(a))

[[ 4  5  6]
 [14 16 18]
 [ 9 17 43]]

[[ 4 14  9]
 [ 5 16 17]
 [ 6 18 43]]


In [19]:
a=np.matrix([[4,5,6],[14,16,18],[9,17,43]])
print(a)
print()
print(a.T)

[[ 4  5  6]
 [14 16 18]
 [ 9 17 43]]

[[ 4 14  9]
 [ 5 16 17]
 [ 6 18 43]]


# swapaxes function

In [22]:
a=np.matrix([[4,5,6],[14,16,18],[9,17,43]])
print(a)
print()
print(np.swapaxes(a,1,0))

[[ 4  5  6]
 [14 16 18]
 [ 9 17 43]]

[[ 4 14  9]
 [ 5 16 17]
 [ 6 18 43]]


In [23]:
a=np.matrix([[4,5,6],[14,16,18],[9,17,43]])
print(a)
print()
print(np.swapaxes(a,0,1))

[[ 4  5  6]
 [14 16 18]
 [ 9 17 43]]

[[ 4 14  9]
 [ 5 16 17]
 [ 6 18 43]]


# Inverse function

In [24]:
a=np.matrix([[3,4],[2,1]])
print(a)
print()
print(np.linalg.inv(a))

[[3 4]
 [2 1]]

[[-0.2  0.8]
 [ 0.4 -0.6]]


# power function

In [29]:
a=np.matrix([[1,2],[4,5]])
print(a)
print()
print(np.linalg.matrix_power(a,2))
print()
print(np.linalg.matrix_power(a,0))
print()
print(np.linalg.matrix_power(a,-2))

[[1 2]
 [4 5]]

[[ 9 12]
 [24 33]]

[[1 0]
 [0 1]]

[[ 3.66666667 -1.33333333]
 [-2.66666667  1.        ]]


# Determinate

In [32]:
a=np.matrix([[1,3,5],[2,4,6],[10,11,12]])
print(a)
print()
print(np.linalg.det(a))

[[ 1  3  5]
 [ 2  4  6]
 [10 11 12]]

0.0
