# iterating in array

# 1D array

In [6]:
import numpy as np
a=np.array([1,2,3,4])
print(a)
print(a.ndim)
print()
for i in a:
    print(i)


[1 2 3 4]
1

1
2
3
4


# 2D array

In [9]:
x=np.array([[1,2,3,4],[5,6,7,8]])
print(x)
print(x.ndim)
print()
for i in x:
    for j in i:
        print(j)

[[1 2 3 4]
 [5 6 7 8]]
2

1
2
3
4
5
6
7
8


# 3D array

In [12]:
x=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(x)
print(x.ndim)
print()
for i in x:
    for j in i:
        for k in j:
            print(k)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
3

1
2
3
4
5
6
7
8
9
10
11
12


# nditer function

In [16]:
x=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(x)
print(x.ndim)
print()
for i in np.nditer(x):
    print(i)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
3

1
2
3
4
5
6
7
8
9
10
11
12


In [17]:
x=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(x)
print(x.ndim)
print()
for i in np.nditer(x,flags=['buffered'],op_dtypes=['S']):
    print(i)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
3

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'
b'11'
b'12'


# ndenumerate function -- gives the index position of the elements also

In [18]:
x=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
for i in np.ndenumerate(x):
    print(i)

((0, 0, 0), 1)
((0, 0, 1), 2)
((0, 0, 2), 3)
((0, 0, 3), 4)
((0, 1, 0), 5)
((0, 1, 1), 6)
((0, 1, 2), 7)
((0, 1, 3), 8)
((0, 2, 0), 9)
((0, 2, 1), 10)
((0, 2, 2), 11)
((0, 2, 3), 12)


In [20]:
x=np.array([[[[2,5,6,7],[8,9,5,6],[2,3,5,6]]]])
print(x)
print(x.ndim)
print()
for i in np.ndenumerate(x):
    print(i)


[[[[2 5 6 7]
   [8 9 5 6]
   [2 3 5 6]]]]
4

((0, 0, 0, 0), 2)
((0, 0, 0, 1), 5)
((0, 0, 0, 2), 6)
((0, 0, 0, 3), 7)
((0, 0, 1, 0), 8)
((0, 0, 1, 1), 9)
((0, 0, 1, 2), 5)
((0, 0, 1, 3), 6)
((0, 0, 2, 0), 2)
((0, 0, 2, 1), 3)
((0, 0, 2, 2), 5)
((0, 0, 2, 3), 6)


# copy vs view  in numpy array

In [21]:
x=np.array([1,2,3,4,5,6])
v=x.view()
print(v)
print()
print(x)

[1 2 3 4 5 6]

[1 2 3 4 5 6]


In [22]:
x=np.array([1,2,3,4,5,6])
v=x.view()
x[3]=56
print(v)
print()
print(x)

[ 1  2  3 56  5  6]

[ 1  2  3 56  5  6]


In [24]:
x=np.array([1,2,3,4,5,6])
v=x.copy()
x[3]=85
print(v)
print()
print(x)

[1 2 3 4 5 6]

[ 1  2  3 85  5  6]


In [26]:
x=np.array([1,2,3,4,5,6])
v=x.copy()
v[3]=85
print(v)
print()
print(x)

[ 1  2  3 85  5  6]

[1 2 3 4 5 6]


# join array

# concatenate function

In [31]:
x=np.array([1,2,3,4])
x1=np.array([5,6,7,8])
v=np.concatenate((x,x1))
print(x)
print()
print(x1)
print()
print(v)

[1 2 3 4]

[5 6 7 8]

[1 2 3 4 5 6 7 8]


In [33]:
x=np.array([[5,0,15,20],[3,6,8,1]])
x1=np.array([[1,2,3,4],[56,67,87,43]])
print(x)
print()
print(x1)
print()
v=np.concatenate((x,x1), axis=1)
print(v)

[[ 5  0 15 20]
 [ 3  6  8  1]]

[[ 1  2  3  4]
 [56 67 87 43]]

[[ 5  0 15 20  1  2  3  4]
 [ 3  6  8  1 56 67 87 43]]


In [34]:
x=np.array([[5,0,15,20],[3,6,8,1]])
x1=np.array([[1,2,3,4],[56,67,87,43]])
print(x)
print()
print(x1)
print()
v=np.concatenate((x,x1), axis=0)
print(v)

[[ 5  0 15 20]
 [ 3  6  8  1]]

[[ 1  2  3  4]
 [56 67 87 43]]

[[ 5  0 15 20]
 [ 3  6  8  1]
 [ 1  2  3  4]
 [56 67 87 43]]


# hstack,vstack and dstack function

In [40]:
x=np.array([1,2,3,4])
x1=np.array([5,6,7,8])
x2=np.array([100,200,300,400])
print(x)
print()
print(x1)
print()
print(x2)
print()
v=np.hstack((x,x1,x2))
print(v)
print()
m=np.vstack((x,x1,x2))
print(m)
print()
p=np.dstack((x,x1,x2))
print(p)

[1 2 3 4]

[5 6 7 8]

[100 200 300 400]

[  1   2   3   4   5   6   7   8 100 200 300 400]

[[  1   2   3   4]
 [  5   6   7   8]
 [100 200 300 400]]

[[[  1   5 100]
  [  2   6 200]
  [  3   7 300]
  [  4   8 400]]]
