# Indexing in Numpy array

In [1]:
import numpy as np
x=np.array([11,22,33,44,55,66,77,88])
print(x[4])

55


In [2]:
import numpy as np
x=np.array([11,22,33,44,55,66,77,88])
print(x[6])

77


In [5]:
x=np.array([11,22,33,44,55,66,77,88])
print(x[-1])

88


In [6]:
x=np.array([11,22,33,44,55,66,77,88])
print(x[-3])

66


# Indexing in 2D array

In [7]:
x=np.array([[11,12],[13,14]])
print(x[1,0])

13


In [8]:
x=np.array([[11,12],[13,14]])
print(x[0,1])

12


In [9]:
x=np.array([[11,12],[13,14]])
print(x[0,0])

11


In [10]:
x=np.array([[1,2,3,4,5],[6,7,8,9,11],[10,12,13,14,15]])
print(x[2,1])

12


In [11]:
x=np.array([[1,2,3,4,5],[6,7,8,9,11],[10,12,13,14,15]])
print(x[1,0])

6


In [12]:
x=np.array([[1,2,3,4,5],[6,7,8,9,11],[10,12,13,14,15]])
print(x[2,3])

14


# Indexing in 3D array

In [15]:
b=np.array([[[11,12],[13,14]],[[15,16],[17,18]]])
print(b)
print(b.ndim)
print(b[1,1,0])

[[[11 12]
  [13 14]]

 [[15 16]
  [17 18]]]
3
17


In [16]:
b=np.array([[[11,12],[13,14]],[[15,16],[17,18]]])
print(b)
print(b.ndim)
print(b[0,1,0])

[[[11 12]
  [13 14]]

 [[15 16]
  [17 18]]]
3
13


In [17]:
b=np.array([[[11,12],[13,14]],[[15,16],[17,18]]])
print(b)
print(b.ndim)
print(b[1,0,1])

[[[11 12]
  [13 14]]

 [[15 16]
  [17 18]]]
3
16


In [22]:
a=np.array([[[3,6,9],[11,22,33],[1,5,7]]])
print(a)
print(a.ndim)
print(a[0,1,2])

[[[ 3  6  9]
  [11 22 33]
  [ 1  5  7]]]
3
33


In [24]:
a=np.array([[[3,6,9],[11,22,33],[1,5,7]]])
print(a)
print(a.ndim)
print(a[0,2,0])

[[[ 3  6  9]
  [11 22 33]
  [ 1  5  7]]]
3
1


# indexing in 5D array

In [26]:
a=np.array([[[[[1,2,3],[4,5,6],[7,8,9]]]]])
print(a)
print(a.ndim)
print(a[0,0,0,1,1])

[[[[[1 2 3]
    [4 5 6]
    [7 8 9]]]]]
5
5


In [27]:
a=np.array([[[[[1,2,3],[4,5,6],[7,8,9]]]]])
print(a)
print(a.ndim)
print(a[0,0,0,2,1])

[[[[[1 2 3]
    [4 5 6]
    [7 8 9]]]]]
5
8


# Slicing in Numpy array

# 1D array

In [2]:
import numpy as np
a=np.array([11,12,13,14,15,16,17,18,19])
print(a[2:7])

[13 14 15 16 17]


In [3]:
import numpy as np
a=np.array([11,12,13,14,15,16,17,18,19])
print(a[2:7:2])

[13 15 17]


In [4]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[:5])

[1 2 3 4 5]


In [5]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[:])

[1 2 3 4 5 6 7 8 9]


In [6]:
a=np.array([11,22,33,54,56,76,87,89,35,66])
print(a[::-1])

[66 35 89 87 76 56 54 33 22 11]


In [7]:
a=np.array([11,22,33,54,56,76,87,89,35,66])
print(a[3:6])

[54 56 76]


#  Slicing in 2D array

In [10]:
import numpy as np
b=np.array([[10,11,12,13,14,15],[20,21,22,23,24,25]])
print(b)
print(b[1,1:4])

[[10 11 12 13 14 15]
 [20 21 22 23 24 25]]
[21 22 23]


In [11]:
import numpy as np
b=np.array([[10,11,12,13,14,15],[20,21,22,23,24,25]])
print(b)
print(b[0,1:4])

[[10 11 12 13 14 15]
 [20 21 22 23 24 25]]
[11 12 13]


In [12]:
import numpy as np
b=np.array([[10,11,12,13,14,15],[20,21,22,23,24,25]])
print(b)
print(b[1,0:5:2])

[[10 11 12 13 14 15]
 [20 21 22 23 24 25]]
[20 22 24]


In [13]:
import numpy as np
b=np.array([[10,11,12,13,14,15],[20,21,22,23,24,25]])
print(b)
print(b[1,::2])

[[10 11 12 13 14 15]
 [20 21 22 23 24 25]]
[20 22 24]


In [14]:
import numpy as np
b=np.array([[10,11,12,13,14,15],[20,21,22,23,24,25]])
print(b)
print(b[1,::-1])

[[10 11 12 13 14 15]
 [20 21 22 23 24 25]]
[25 24 23 22 21 20]


In [15]:
import numpy as np
b=np.array([[10,11,12,13,14,15],[20,21,22,23,24,25]])
print(b)
print(b[0,::-1])

[[10 11 12 13 14 15]
 [20 21 22 23 24 25]]
[15 14 13 12 11 10]


# slicing in 3D array

In [17]:
a=np.array([[[1,2,3,7,9],[4,5,6,9,10],[7,8,9,1,2]]])
print(a)
print(a[0,1,1:4])

[[[ 1  2  3  7  9]
  [ 4  5  6  9 10]
  [ 7  8  9  1  2]]]
[5 6 9]


In [22]:
a=np.array([[[1,2,3,7,9],[4,5,6,9,10],[7,8,9,1,2]]])
print(a[0,2,::2])

[7 9 2]


In [23]:
a=np.array([[[1,2,3,7,9],[4,5,6,9,10],[7,8,9,1,2]]])
print(a[0,2,::-1])

[2 1 9 8 7]


In [24]:
a=np.array([[[1,2,3,7,9],[4,5,6,9,10],[7,8,9,1,2]]])
print(a[0,1,::-1])

[10  9  6  5  4]
